// SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause)
/*
 * Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
 */

#ifndef _DT_BINDINGS_SCMI_VERSAL2_RESET_H
#define _DT_BINDINGS_SCMI_VERSAL2_RESET_H

/* SCMI reset domain ids for Versal Gen2 (usable in device tree). */

#define SCMI_RST_VERSAL2_QSPI			0
#define SCMI_RST_VERSAL2_OSPI			1
#define SCMI_RST_VERSAL2_SDIO_0			2
#define SCMI_RST_VERSAL2_SDIO_1			3
#define SCMI_RST_VERSAL2_GPIO_PMC		4
#define SCMI_RST_VERSAL2_GEM_0			5
#define SCMI_RST_VERSAL2_GEM_1			6
#define SCMI_RST_VERSAL2_SPARE			7
#define SCMI_RST_VERSAL2_USB_0			8
#define SCMI_RST_VERSAL2_UART_0			9
#define SCMI_RST_VERSAL2_UART_1			10
#define SCMI_RST_VERSAL2_SPI_0			11
#define SCMI_RST_VERSAL2_SPI_1			12
#define SCMI_RST_VERSAL2_CAN_FD_0		13
#define SCMI_RST_VERSAL2_CAN_FD_1		14
#define SCMI_RST_VERSAL2_GPIO_LPD		15
#define SCMI_RST_VERSAL2_TTC_0			16
#define SCMI_RST_VERSAL2_TTC_1			17
#define SCMI_RST_VERSAL2_TTC_2			18
#define SCMI_RST_VERSAL2_TTC_3			19
#define SCMI_RST_VERSAL2_UDH_DRD		20
#define SCMI_RST_VERSAL2_UFS_PHY		21
#define SCMI_RST_VERSAL2_USB_1			22
#define SCMI_RST_VERSAL2_UFS			23
#define SCMI_RST_VERSAL2_DC			24
#define SCMI_RST_VERSAL2_GPU			25
#define SCMI_RST_VERSAL2_GPU_RECOV		26
#define SCMI_RST_VERSAL2_UDH_AUX		27
#define SCMI_RST_VERSAL2_UDH_DP			28
#define SCMI_RST_VERSAL2_UDH_HDCPRAM		29
#define SCMI_RST_VERSAL2_MMI_GEM		30
#define SCMI_RST_VERSAL2_MMI_GEM_CFG		31
#define SCMI_RST_VERSAL2_MMI_GEM_TSU		32
#define SCMI_RST_VERSAL2_ADMA_0			33
#define SCMI_RST_VERSAL2_ADMA_1			34
#define SCMI_RST_VERSAL2_ADMA_2			35
#define SCMI_RST_VERSAL2_ADMA_3			36
#define SCMI_RST_VERSAL2_ADMA_4			37
#define SCMI_RST_VERSAL2_ADMA_5			38
#define SCMI_RST_VERSAL2_ADMA_6			39
#define SCMI_RST_VERSAL2_ADMA_7			40
#define SCMI_RST_VERSAL2_PMCDBG			41
#define SCMI_RST_VERSAL2_DBG_FPD		42
#define SCMI_RST_VERSAL2_DBG_LPD		43
#define SCMI_RST_VERSAL2_PMC_POR		44
#define SCMI_RST_VERSAL2_PS_POR			45
#define SCMI_RST_VERSAL2_PL_POR			46
#define SCMI_RST_VERSAL2_NOC_POR		47
#define SCMI_RST_VERSAL2_FPD_POR		48
#define SCMI_RST_VERSAL2_CPM_POR		49
#define SCMI_RST_VERSAL2_PMC			50
#define SCMI_RST_VERSAL2_PS_SRST		51
#define SCMI_RST_VERSAL2_PL_SRST		52
#define SCMI_RST_VERSAL2_NOC			53
#define SCMI_RST_VERSAL2_NPI			54
#define SCMI_RST_VERSAL2_SYS_RST_1		55
#define SCMI_RST_VERSAL2_SYS_RST_2		56
#define SCMI_RST_VERSAL2_SYS_RST_3		57
#define SCMI_RST_VERSAL2_FPD			58
#define SCMI_RST_VERSAL2_PL0			59
#define SCMI_RST_VERSAL2_PL1			60
#define SCMI_RST_VERSAL2_PL2			61
#define SCMI_RST_VERSAL2_PL3			62
#define SCMI_RST_VERSAL2_ACPU_GIC		63
#define SCMI_RST_VERSAL2_SYSMON_PMC_SEQ_RST	64
#define SCMI_RST_VERSAL2_SYSMON_PMC_CFG_RST	65
#define SCMI_RST_VERSAL2_SYSMON_FPD_CFG_RST	66
#define SCMI_RST_VERSAL2_SYSMON_FPD_SEQ_RST	67
#define SCMI_RST_VERSAL2_SYSMON_LPD		68
#define SCMI_RST_VERSAL2_PDMA_RST1		69
#define SCMI_RST_VERSAL2_PDMA_RST0		70
#define SCMI_RST_VERSAL2_ADMA			71
#define SCMI_RST_VERSAL2_TIMESTAMP		72
#define SCMI_RST_VERSAL2_OCM			73
#define SCMI_RST_VERSAL2_IPI			74
#define SCMI_RST_VERSAL2_SBI			75
#define SCMI_RST_VERSAL2_LPD			76
#define SCMI_RST_VERSAL2_CPM			77
#define SCMI_RST_VERSAL2_CMN			78
#define SCMI_RST_VERSAL2_EIO_UART_0		79
#define SCMI_RST_VERSAL2_EIO_UART_1		80
#define SCMI_RST_VERSAL2_EIO_UART_2		81
#define SCMI_RST_VERSAL2_EIO_SPI_0		82
#define SCMI_RST_VERSAL2_EIO_SPI_1		83
#define SCMI_RST_VERSAL2_EIO_SPI_2		84
#define SCMI_RST_VERSAL2_EIO_SPI_3		85
#define SCMI_RST_VERSAL2_GPIO_EIO		86

#endif /* _DT_BINDINGS_SCMI_VERSAL2_RESET_H */
